$('#slider').owlCarousel({
    loop:true,
    autoheight:true,
    margin:15,
    items:3,
    nav:false,
    autoplay:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:3
        }
    }
})